### PR TITLE
fix 'show worst'

### PR DESCRIPTION
**Pull request by AugustT**
The code was only showing the WORST match. Removing the indexing shows all predictions

### CODE REVIEW

**Comment by sourcedexter** [comment]
What I have done is to sort the array in ascending order and reversed it by using the [::-1] construct. Thus, it does not show the worst match. It is working correctly.

**Comment by AugustT** [comment]
This issue exists for me and the worst fit is shown, I have made no edit to your code. For me at least it does not work correctly.

**Comment by AugustT** [comment]
Could this be a windows issue?

**Comment by sourcedexter** [comment]
there are many people who have used this on Windows OS. I can assure you that the code is correct. there is a chance that the labels file is wrong or a wrong model is being used. 

It is not the fault of this code. I have used this code at multiple places and it's running accurately (  94% accurate in fact). Please do check the files being used. They might reveal some mistake that you might have missed.

**Comment by AugustT** [comment]
Okay, I'll do some digging and see if I can find the source of the issue

**Comment by AugustT** [comment]
I think I found the issue, when I copied the i introduced some indentation issues. Thanks for the code!

**Comment by sourcedexter** [comment]
Awesome! you're welcome.

**Pull request closed without merging**
