### PR TITLE
change tf.train.SummaryWriter to tf.summary.FileWriter

### PR DESCRIPTION
**Pull request by plusoneee**
Summary functions have been consolidated under the tf.summary namespace.
so I change  tf.train.SummaryWriter to tf.summary.FileWriter

### CODE REVIEW

**Comment by sourcedexter** [comment]
may I know on which OS this was tested?

**Comment by plusoneee** [comment]
I use macOS ,
Source of the materials:
https://stackoverflow.com/questions/41482913/module-object-has-no-attribute-summarywriter

**Comment by Plusone7** [comment]
Really appreciate that you take your time for helping this problem.
I will keep trying
Thank you so much.

2017-12-04 13:56 GMT+08:00 Akshay Pai <notifications@github.com>:

**Comment by sourcedexter** [comment]
okay, cool. thanks!

**Pull request merged**
